import { BlockData, BlockCategory } from '@/types'

export const BLOCKS: BlockData[] = [
  // ========== 建筑方块 ==========
  { id: 'minecraft:stone', name: 'Stone', nameZh: '石头', color: '#808080', hardness: 1.5, transparent: false, category: 'building' },
  { id: 'minecraft:granite', name: 'Granite', nameZh: '花岗岩', color: '#9A6B52', hardness: 1.5, transparent: false, category: 'building' },
  { id: 'minecraft:diorite', name: 'Diorite', nameZh: '闪长岩', color: '#D4D4D4', hardness: 1.5, transparent: false, category: 'building' },
  { id: 'minecraft:andesite', name: 'Andesite', nameZh: '安山岩', color: '#8A8A8A', hardness: 1.5, transparent: false, category: 'building' },
  { id: 'minecraft:deepslate', name: 'Deepslate', nameZh: '深板岩', color: '#3D3D4A', hardness: 3.0, transparent: false, category: 'building' },
  { id: 'minecraft:cobbled_deepslate', name: 'Cobbled Deepslate', nameZh: '深板岩圆石', color: '#4A4A5A', hardness: 3.5, transparent: false, category: 'building' },
  { id: 'minecraft:tuff', name: 'Tuff', nameZh: '凝灰岩', color: '#5A5A5A', hardness: 1.5, transparent: false, category: 'building' },
  { id: 'minecraft:calcite', name: 'Calcite', nameZh: '方解石', color: '#E8E8E8', hardness: 0.75, transparent: false, category: 'building' },
  { id: 'minecraft:dripstone_block', name: 'Dripstone Block', nameZh: '滴水石块', color: '#8B6B4B', hardness: 1.5, transparent: false, category: 'building' },
  { id: 'minecraft:pointed_dripstone', name: 'Pointed Dripstone', nameZh: '尖端滴水石', color: '#9B7B5B', hardness: 1.0, transparent: true, category: 'building' },
  { id: 'minecraft:cobblestone', name: 'Cobblestone', nameZh: '圆石', color: '#6B6B6B', hardness: 2.0, transparent: false, category: 'building' },
  { id: 'minecraft:mossy_cobblestone', name: 'Mossy Cobblestone', nameZh: '苔圆石', color: '#5A6B5A', hardness: 2.0, transparent: false, category: 'building' },
  { id: 'minecraft:smooth_stone', name: 'Smooth Stone', nameZh: '平滑石头', color: '#909090', hardness: 2.0, transparent: false, category: 'building' },
  { id: 'minecraft:oak_planks', name: 'Oak Planks', nameZh: '橡木木板', color: '#BC9862', hardness: 2.0, transparent: false, category: 'building' },
  { id: 'minecraft:spruce_planks', name: 'Spruce Planks', nameZh: '云杉木板', color: '#6B5430', hardness: 2.0, transparent: false, category: 'building' },
  { id: 'minecraft:birch_planks', name: 'Birch Planks', nameZh: '桦木木板', color: '#D4C59E', hardness: 2.0, transparent: false, category: 'building' },
  { id: 'minecraft:jungle_planks', name: 'Jungle Planks', nameZh: '丛林木板', color: '#9B7B5A', hardness: 2.0, transparent: false, category: 'building' },
  { id: 'minecraft:acacia_planks', name: 'Acacia Planks', nameZh: '金合欢木板', color: '#A45A3A', hardness: 2.0, transparent: false, category: 'building' },
  { id: 'minecraft:dark_oak_planks', name: 'Dark Oak Planks', nameZh: '深色橡木木板', color: '#4A3728', hardness: 2.0, transparent: false, category: 'building' },
  { id: 'minecraft:mangrove_planks', name: 'Mangrove Planks', nameZh: '红树木板', color: '#6B4A3A', hardness: 2.0, transparent: false, category: 'building' },
  { id: 'minecraft:bamboo_planks', name: 'Bamboo Planks', nameZh: '竹木板', color: '#B5A040', hardness: 2.0, transparent: false, category: 'building' },
  { id: 'minecraft:cherry_planks', name: 'Cherry Planks', nameZh: '樱花木板', color: '#D4A0A0', hardness: 2.0, transparent: false, category: 'building' },
  { id: 'minecraft:crimson_planks', name: 'Crimson Planks', nameZh: '绯红木板', color: '#8B3A4A', hardness: 2.0, transparent: false, category: 'building' },
  { id: 'minecraft:warped_planks', name: 'Warped Planks', nameZh: '扭曲木板', color: '#3A8B7B', hardness: 2.0, transparent: false, category: 'building' },
  { id: 'minecraft:bricks', name: 'Bricks', nameZh: '砖块', color: '#9B5B3C', hardness: 2.0, transparent: false, category: 'building' },
  { id: 'minecraft:stone_bricks', name: 'Stone Bricks', nameZh: '石砖', color: '#7A7A7A', hardness: 1.5, transparent: false, category: 'building' },
  { id: 'minecraft:mossy_stone_bricks', name: 'Mossy Stone Bricks', nameZh: '苔石砖', color: '#6A7A6A', hardness: 1.5, transparent: false, category: 'building' },
  { id: 'minecraft:cracked_stone_bricks', name: 'Cracked Stone Bricks', nameZh: '裂纹石砖', color: '#7A7A7A', hardness: 1.5, transparent: false, category: 'building' },
  { id: 'minecraft:chiseled_stone_bricks', name: 'Chiseled Stone Bricks', nameZh: '錾制石砖', color: '#7A7A7A', hardness: 1.5, transparent: false, category: 'building' },
  { id: 'minecraft:packed_mud', name: 'Packed Mud', nameZh: '紧压泥土', color: '#7B5B4B', hardness: 1.0, transparent: false, category: 'building' },
  { id: 'minecraft:mud_bricks', name: 'Mud Bricks', nameZh: '泥砖', color: '#6B4B3B', hardness: 1.5, transparent: false, category: 'building' },
  { id: 'minecraft:sandstone', name: 'Sandstone', nameZh: '砂岩', color: '#E8D4A8', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:red_sandstone', name: 'Red Sandstone', nameZh: '红砂岩', color: '#D47A3A', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:cut_sandstone', name: 'Cut Sandstone', nameZh: '切制砂岩', color: '#E8D4A8', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:cut_red_sandstone', name: 'Cut Red Sandstone', nameZh: '切制红砂岩', color: '#D47A3A', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:prismarine', name: 'Prismarine', nameZh: '海晶石', color: '#4A8B7A', hardness: 1.5, transparent: false, category: 'building' },
  { id: 'minecraft:prismarine_bricks', name: 'Prismarine Bricks', nameZh: '海晶砖', color: '#5A9B8A', hardness: 1.5, transparent: false, category: 'building' },
  { id: 'minecraft:dark_prismarine', name: 'Dark Prismarine', nameZh: '暗海晶石', color: '#2A5B4A', hardness: 1.5, transparent: false, category: 'building' },
  { id: 'minecraft:sea_lantern', name: 'Sea Lantern', nameZh: '海灯笼', color: '#A8D8EA', hardness: 0.3, transparent: true, category: 'building' },
  { id: 'minecraft:end_stone_bricks', name: 'End Stone Bricks', nameZh: '末地石砖', color: '#E8E8CC', hardness: 3.0, transparent: false, category: 'building' },
  { id: 'minecraft:purpur_block', name: 'Purpur Block', nameZh: '紫珀块', color: '#9B7BBF', hardness: 1.5, transparent: false, category: 'building' },
  { id: 'minecraft:quartz_block', name: 'Quartz Block', nameZh: '石英块', color: '#E8E8E8', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:chiseled_quartz_block', name: 'Chiseled Quartz Block', nameZh: '錾制石英块', color: '#E8E8E8', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:quartz_pillar', name: 'Quartz Pillar', nameZh: '石英柱', color: '#E8E8E8', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:smooth_quartz', name: 'Smooth Quartz', nameZh: '平滑石英', color: '#E8E8E8', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:glass', name: 'Glass', nameZh: '玻璃', color: '#CCE5FF', hardness: 0.3, transparent: true, category: 'building' },
  { id: 'minecraft:tinted_glass', name: 'Tinted Glass', nameZh: '遮光玻璃', color: '#4A4A5A', hardness: 0.3, transparent: true, category: 'building' },
  { id: 'minecraft:glass_pane', name: 'Glass Pane', nameZh: '玻璃板', color: '#CCE5FF', hardness: 0.3, transparent: true, category: 'building' },
  { id: 'minecraft:iron_bars', name: 'Iron Bars', nameZh: '铁栏杆', color: '#404040', hardness: 5.0, transparent: true, category: 'building' },
  { id: 'minecraft:white_wool', name: 'White Wool', nameZh: '白色羊毛', color: '#F0F0F0', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:orange_wool', name: 'Orange Wool', nameZh: '橙色羊毛', color: '#E57A1A', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:magenta_wool', name: 'Magenta Wool', nameZh: '品红羊毛', color: '#B41AB4', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:light_blue_wool', name: 'Light Blue Wool', nameZh: '淡蓝色羊毛', color: '#4A9AD4', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:yellow_wool', name: 'Yellow Wool', nameZh: '黄色羊毛', color: '#E8D41A', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:lime_wool', name: 'Lime Wool', nameZh: '黄绿色羊毛', color: '#7AC41A', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:pink_wool', name: 'Pink Wool', nameZh: '粉色羊毛', color: '#D49AC4', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:gray_wool', name: 'Gray Wool', nameZh: '灰色羊毛', color: '#4A4A4A', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:light_gray_wool', name: 'Light Gray Wool', nameZh: '淡灰色羊毛', color: '#9A9A9A', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:cyan_wool', name: 'Cyan Wool', nameZh: '青色羊毛', color: '#1A9A9A', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:purple_wool', name: 'Purple Wool', nameZh: '紫色羊毛', color: '#6A1A9A', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:blue_wool', name: 'Blue Wool', nameZh: '蓝色羊毛', color: '#1A1A9A', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:brown_wool', name: 'Brown Wool', nameZh: '棕色羊毛', color: '#6B4A2A', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:green_wool', name: 'Green Wool', nameZh: '绿色羊毛', color: '#4A8A1A', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:red_wool', name: 'Red Wool', nameZh: '红色羊毛', color: '#9A1A1A', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:black_wool', name: 'Black Wool', nameZh: '黑色羊毛', color: '#1A1A1A', hardness: 0.8, transparent: false, category: 'building' },
  { id: 'minecraft:white_concrete', name: 'White Concrete', nameZh: '白色混凝土', color: '#D9D9D9', hardness: 1.8, transparent: false, category: 'building' },
  { id: 'minecraft:orange_concrete', name: 'Orange Concrete', nameZh: '橙色混凝土', color: '#E57A1A', hardness: 1.8, transparent: false, category: 'building' },
  { id: 'minecraft:magenta_concrete', name: 'Magenta Concrete', nameZh: '品红混凝土', color: '#A41A9A', hardness: 1.8, transparent: false, category: 'building' },
  { id: 'minecraft:light_blue_concrete', name: 'Light Blue Concrete', nameZh: '淡蓝色混凝土', color: '#3A8AC4', hardness: 1.8, transparent: false, category: 'building' },
  { id: 'minecraft:yellow_concrete', name: 'Yellow Concrete', nameZh: '黄色混凝土', color: '#D4C41A', hardness: 1.8, transparent: false, category: 'building' },
  { id: 'minecraft:lime_concrete', name: 'Lime Concrete', nameZh: '黄绿色混凝土', color: '#6AB41A', hardness: 1.8, transparent: false, category: 'building' },
  { id: 'minecraft:pink_concrete', name: 'Pink Concrete', nameZh: '粉色混凝土', color: '#D48AB4', hardness: 1.8, transparent: false, category: 'building' },
  { id: 'minecraft:gray_concrete', name: 'Gray Concrete', nameZh: '灰色混凝土', color: '#3A3A3A', hardness: 1.8, transparent: false, category: 'building' },
  { id: 'minecraft:light_gray_concrete', name: 'Light Gray Concrete', nameZh: '淡灰色混凝土', color: '#8A8A8A', hardness: 1.8, transparent: false, category: 'building' },
  { id: 'minecraft:cyan_concrete', name: 'Cyan Concrete', nameZh: '青色混凝土', color: '#1A8A8A', hardness: 1.8, transparent: false, category: 'building' },
  { id: 'minecraft:purple_concrete', name: 'Purple Concrete', nameZh: '紫色混凝土', color: '#5A1A8A', hardness: 1.8, transparent: false, category: 'building' },
  { id: 'minecraft:blue_concrete', name: 'Blue Concrete', nameZh: '蓝色混凝土', color: '#1A1A8A', hardness: 1.8, transparent: false, category: 'building' },
  { id: 'minecraft:brown_concrete', name: 'Brown Concrete', nameZh: '棕色混凝土', color: '#5B3A1A', hardness: 1.8, transparent: false, category: 'building' },
  { id: 'minecraft:green_concrete', name: 'Green Concrete', nameZh: '绿色混凝土', color: '#3A7A1A', hardness: 1.8, transparent: false, category: 'building' },
  { id: 'minecraft:red_concrete', name: 'Red Concrete', nameZh: '红色混凝土', color: '#8A1A1A', hardness: 1.8, transparent: false, category: 'building' },
  { id: 'minecraft:black_concrete', name: 'Black Concrete', nameZh: '黑色混凝土', color: '#0D0D0D', hardness: 1.8, transparent: false, category: 'building' },
  { id: 'minecraft:white_terracotta', name: 'White Terracotta', nameZh: '白色陶瓦', color: '#D4C4B4', hardness: 1.25, transparent: false, category: 'building' },
  { id: 'minecraft:orange_terracotta', name: 'Orange Terracotta', nameZh: '橙色陶瓦', color: '#B45A2A', hardness: 1.25, transparent: false, category: 'building' },
  { id: 'minecraft:magenta_terracotta', name: 'Magenta Terracotta', nameZh: '品红陶瓦', color: '#9A3A9A', hardness: 1.25, transparent: false, category: 'building' },
  { id: 'minecraft:light_blue_terracotta', name: 'Light Blue Terracotta', nameZh: '淡蓝色陶瓦', color: '#6A7AA4', hardness: 1.25, transparent: false, category: 'building' },
  { id: 'minecraft:yellow_terracotta', name: 'Yellow Terracotta', nameZh: '黄色陶瓦', color: '#C4A43A', hardness: 1.25, transparent: false, category: 'building' },
  { id: 'minecraft:lime_terracotta', name: 'Lime Terracotta', nameZh: '黄绿色陶瓦', color: '#8A9A2A', hardness: 1.25, transparent: false, category: 'building' },
  { id: 'minecraft:pink_terracotta', name: 'Pink Terracotta', nameZh: '粉色陶瓦', color: '#B48A8A', hardness: 1.25, transparent: false, category: 'building' },
  { id: 'minecraft:gray_terracotta', name: 'Gray Terracotta', nameZh: '灰色陶瓦', color: '#3A2A2A', hardness: 1.25, transparent: false, category: 'building' },
  { id: 'minecraft:light_gray_terracotta', name: 'Light Gray Terracotta', nameZh: '淡灰色陶瓦', color: '#8A7A6A', hardness: 1.25, transparent: false, category: 'building' },
  { id: 'minecraft:cyan_terracotta', name: 'Cyan Terracotta', nameZh: '青色陶瓦', color: '#3A5A5A', hardness: 1.25, transparent: false, category: 'building' },
  { id: 'minecraft:purple_terracotta', name: 'Purple Terracotta', nameZh: '紫色陶瓦', color: '#5A2A5A', hardness: 1.25, transparent: false, category: 'building' },
  { id: 'minecraft:blue_terracotta', name: 'Blue Terracotta', nameZh: '蓝色陶瓦', color: '#3A3A5A', hardness: 1.25, transparent: false, category: 'building' },
  { id: 'minecraft:brown_terracotta', name: 'Brown Terracotta', nameZh: '棕色陶瓦', color: '#4A2A1A', hardness: 1.25, transparent: false, category: 'building' },
  { id: 'minecraft:green_terracotta', name: 'Green Terracotta', nameZh: '绿色陶瓦', color: '#4A5A2A', hardness: 1.25, transparent: false, category: 'building' },
  { id: 'minecraft:red_terracotta', name: 'Red Terracotta', nameZh: '红色陶瓦', color: '#8A3A2A', hardness: 1.25, transparent: false, category: 'building' },
  { id: 'minecraft:black_terracotta', name: 'Black Terracotta', nameZh: '黑色陶瓦', color: '#1A1515', hardness: 1.25, transparent: false, category: 'building' },
  { id: 'minecraft:terracotta', name: 'Terracotta', nameZh: '陶瓦', color: '#9B6B5A', hardness: 1.25, transparent: false, category: 'building' },
  { id: 'minecraft:clay', name: 'Clay', nameZh: '粘土块', color: '#9AA4A4', hardness: 0.6, transparent: false, category: 'building' },
  { id: 'minecraft:hardened_clay', name: 'Hardened Clay', nameZh: '硬化粘土', color: '#9B6B5A', hardness: 1.25, transparent: false, category: 'building' },
  { id: 'minecraft:raw_iron_block', name: 'Raw Iron Block', nameZh: '粗铁块', color: '#C8A888', hardness: 5.0, transparent: false, category: 'building' },
  { id: 'minecraft:raw_gold_block', name: 'Raw Gold Block', nameZh: '粗金块', color: '#D4B428', hardness: 3.0, transparent: false, category: 'building' },
  { id: 'minecraft:raw_copper_block', name: 'Raw Copper Block', nameZh: '粗铜块', color: '#B87850', hardness: 5.0, transparent: false, category: 'building' },
  { id: 'minecraft:obsidian', name: 'Obsidian', nameZh: '黑曜石', color: '#1a1a2e', hardness: 50, transparent: false, category: 'building' },
  { id: 'minecraft:crying_obsidian', name: 'Crying Obsidian', nameZh: '哭泣黑曜石', color: '#2a1a4e', hardness: 50, transparent: false, category: 'building' },

  // ========== 自然方块 ==========
  { id: 'minecraft:grass_block', name: 'Grass Block', nameZh: '草方块', color: '#5D8C3E', hardness: 0.6, transparent: false, category: 'natural' },
  { id: 'minecraft:grass', name: 'Grass', nameZh: '草', color: '#5D8C3E', hardness: 0.0, transparent: true, category: 'natural' },
  { id: 'minecraft:tall_grass', name: 'Tall Grass', nameZh: '高草', color: '#5D8C3E', hardness: 0.0, transparent: true, category: 'natural' },
  { id: 'minecraft:fern', name: 'Fern', nameZh: '蕨', color: '#5D8C3E', hardness: 0.0, transparent: true, category: 'natural' },
  { id: 'minecraft:dirt', name: 'Dirt', nameZh: '泥土', color: '#866043', hardness: 0.5, transparent: false, category: 'natural' },
  { id: 'minecraft:coarse_dirt', name: 'Coarse Dirt', nameZh: '粗糙泥土', color: '#7B5B4B', hardness: 0.5, transparent: false, category: 'natural' },
  { id: 'minecraft:rooted_dirt', name: 'Rooted Dirt', nameZh: '根土', color: '#7B6043', hardness: 0.5, transparent: false, category: 'natural' },
  { id: 'minecraft:moss_block', name: 'Moss Block', nameZh: '苔藓块', color: '#5A7A4A', hardness: 0.1, transparent: false, category: 'natural' },
  { id: 'minecraft:podzol', name: 'Podzol', nameZh: '灰化土', color: '#5B4030', hardness: 0.5, transparent: false, category: 'natural' },
  { id: 'minecraft:mycelium', name: 'Mycelium', nameZh: '菌丝土', color: '#7B5B7A', hardness: 0.5, transparent: false, category: 'natural' },
  { id: 'minecraft:mud', name: 'Mud', nameZh: '泥巴', color: '#5B4030', hardness: 0.5, transparent: false, category: 'natural' },
  { id: 'minecraft:clay', name: 'Clay', nameZh: '粘土', color: '#9AA4A4', hardness: 0.6, transparent: false, category: 'natural' },
  { id: 'minecraft:sand', name: 'Sand', nameZh: '沙子', color: '#DBD3A0', hardness: 0.5, transparent: false, category: 'natural' },
  { id: 'minecraft:red_sand', name: 'Red Sand', nameZh: '红沙', color: '#D47A3A', hardness: 0.5, transparent: false, category: 'natural' },
  { id: 'minecraft:gravel', name: 'Gravel', nameZh: '沙砾', color: '#8A8A8A', hardness: 0.6, transparent: false, category: 'natural' },
  { id: 'minecraft:soul_sand', name: 'Soul Sand', nameZh: '灵魂沙', color: '#5B4030', hardness: 0.5, transparent: false, category: 'natural' },
  { id: 'minecraft:soul_soil', name: 'Soul Soil', nameZh: '灵魂土', color: '#4B3020', hardness: 0.4, transparent: false, category: 'natural' },
  { id: 'minecraft:end_stone', name: 'End Stone', nameZh: '末地石', color: '#E8E8CC', hardness: 3, transparent: false, category: 'natural' },
  { id: 'minecraft:bedrock', name: 'Bedrock', nameZh: '基岩', color: '#2A2A2A', hardness: -1, transparent: false, category: 'natural' },
  { id: 'minecraft:netherrack', name: 'Netherrack', nameZh: '下界岩', color: '#8B3A3A', hardness: 0.4, transparent: false, category: 'natural' },
  { id: 'minecraft:nether_bricks', name: 'Nether Bricks', nameZh: '下界砖', color: '#2A1A1A', hardness: 2.0, transparent: false, category: 'natural' },
  { id: 'minecraft:crimson_nylium', name: 'Crimson Nylium', nameZh: '绯红菌髓', color: '#8B2A3A', hardness: 0.4, transparent: false, category: 'natural' },
  { id: 'minecraft:warped_nylium', name: 'Warped Nylium', nameZh: '扭曲菌髓', color: '#2A8B7A', hardness: 0.4, transparent: false, category: 'natural' },
  { id: 'minecraft:basalt', name: 'Basalt', nameZh: '玄武岩', color: '#3D3D4A', hardness: 1.25, transparent: false, category: 'natural' },
  { id: 'minecraft:blackstone', name: 'Blackstone', nameZh: '黑石', color: '#1a1a1a', hardness: 2, transparent: false, category: 'natural' },
  { id: 'minecraft:polished_basalt', name: 'Polished Basalt', nameZh: '磨制玄武岩', color: '#4D4D5A', hardness: 1.25, transparent: false, category: 'natural' },
  { id: 'minecraft:polished_blackstone', name: 'Polished Blackstone', nameZh: '磨制黑石', color: '#2A2A2A', hardness: 2, transparent: false, category: 'natural' },
  { id: 'minecraft:polished_blackstone_bricks', name: 'Polished Blackstone Bricks', nameZh: '磨制黑石砖', color: '#2A2A2A', hardness: 2, transparent: false, category: 'natural' },
  { id: 'minecraft:cracked_polished_blackstone_bricks', name: 'Cracked Polished Blackstone Bricks', nameZh: '裂纹磨制黑石砖', color: '#2A2A2A', hardness: 2, transparent: false, category: 'natural' },
  { id: 'minecraft:glowstone', name: 'Glowstone', nameZh: '荧石', color: '#D4A83A', hardness: 0.3, transparent: false, category: 'natural' },
  { id: 'minecraft:magma_block', name: 'Magma Block', nameZh: '岩浆块', color: '#9B3A1A', hardness: 0.5, transparent: false, category: 'natural' },
  { id: 'minecraft:ancient_debris', name: 'Ancient Debris', nameZh: '远古残骸', color: '#5A4A3A', hardness: 50, transparent: false, category: 'natural' },
  { id: 'minecraft:nether_gold_ore', name: 'Nether Gold Ore', nameZh: '下界金矿', color: '#8B5A2A', hardness: 3.0, transparent: false, category: 'natural' },
  { id: 'minecraft:nether_quartz_ore', name: 'Nether Quartz Ore', nameZh: '下界石英矿', color: '#D4C4B4', hardness: 3.0, transparent: false, category: 'natural' },
  { id: 'minecraft:oak_log', name: 'Oak Log', nameZh: '橡木原木', color: '#7B5B3A', hardness: 2.0, transparent: false, category: 'natural' },
  { id: 'minecraft:spruce_log', name: 'Spruce Log', nameZh: '云杉原木', color: '#4A3728', hardness: 2.0, transparent: false, category: 'natural' },
  { id: 'minecraft:birch_log', name: 'Birch Log', nameZh: '桦木原木', color: '#D4D4B4', hardness: 2.0, transparent: false, category: 'natural' },
  { id: 'minecraft:jungle_log', name: 'Jungle Log', nameZh: '丛林原木', color: '#6B5B3A', hardness: 2.0, transparent: false, category: 'natural' },
  { id: 'minecraft:acacia_log', name: 'Acacia Log', nameZh: '金合欢原木', color: '#6B4A3A', hardness: 2.0, transparent: false, category: 'natural' },
  { id: 'minecraft:dark_oak_log', name: 'Dark Oak Log', nameZh: '深色橡木原木', color: '#3A2A1A', hardness: 2.0, transparent: false, category: 'natural' },
  { id: 'minecraft:mangrove_log', name: 'Mangrove Log', nameZh: '红树原木', color: '#5B3A2A', hardness: 2.0, transparent: false, category: 'natural' },
  { id: 'minecraft:cherry_log', name: 'Cherry Log', nameZh: '樱花原木', color: '#9A7B7A', hardness: 2.0, transparent: false, category: 'natural' },
  { id: 'minecraft:crimson_stem', name: 'Crimson Stem', nameZh: '绯红茎', color: '#7B3A4A', hardness: 2.0, transparent: false, category: 'natural' },
  { id: 'minecraft:warped_stem', name: 'Warped Stem', nameZh: '扭曲茎', color: '#3A7B7A', hardness: 2.0, transparent: false, category: 'natural' },
  { id: 'minecraft:oak_leaves', name: 'Oak Leaves', nameZh: '橡树树叶', color: '#3A7A2A', hardness: 0.2, transparent: true, category: 'natural' },
  { id: 'minecraft:spruce_leaves', name: 'Spruce Leaves', nameZh: '云杉树叶', color: '#2A5A1A', hardness: 0.2, transparent: true, category: 'natural' },
  { id: 'minecraft:birch_leaves', name: 'Birch Leaves', nameZh: '桦木树叶', color: '#4A8A2A', hardness: 0.2, transparent: true, category: 'natural' },
  { id: 'minecraft:jungle_leaves', name: 'Jungle Leaves', nameZh: '丛林树叶', color: '#3A7A2A', hardness: 0.2, transparent: true, category: 'natural' },
  { id: 'minecraft:acacia_leaves', name: 'Acacia Leaves', nameZh: '金合欢树叶', color: '#5A9A2A', hardness: 0.2, transparent: true, category: 'natural' },
  { id: 'minecraft:dark_oak_leaves', name: 'Dark Oak Leaves', nameZh: '深色橡木树叶', color: '#2A5A1A', hardness: 0.2, transparent: true, category: 'natural' },
  { id: 'minecraft:mangrove_leaves', name: 'Mangrove Leaves', nameZh: '红树树叶', color: '#4A8A3A', hardness: 0.2, transparent: true, category: 'natural' },
  { id: 'minecraft:cherry_leaves', name: 'Cherry Leaves', nameZh: '樱花树叶', color: '#B4A0A0', hardness: 0.2, transparent: true, category: 'natural' },
  { id: 'minecraft:azalea_leaves', name: 'Azalea Leaves', nameZh: '杜鹃花叶', color: '#6A9A4A', hardness: 0.2, transparent: true, category: 'natural' },
  { id: 'minecraft:flowering_azalea_leaves', name: 'Flowering Azalea Leaves', nameZh: '开花杜鹃花叶', color: '#7AAA5A', hardness: 0.2, transparent: true, category: 'natural' },
  { id: 'minecraft:vine', name: 'Vine', nameZh: '藤蔓', color: '#3A7A2A', hardness: 0.0, transparent: true, category: 'natural' },
  { id: 'minecraft:lily_of_the_valley', name: 'Lily of the Valley', nameZh: '铃兰', color: '#F0F0F0', hardness: 0.0, transparent: false, category: 'natural' },
  { id: 'minecraft:spore_blossom', name: 'Spore Blossom', nameZh: '孢子花', color: '#A4D4A4', hardness: 0.0, transparent: true, category: 'natural' },
  { id: 'minecraft:hanging_roots', name: 'Hanging Roots', nameZh: '垂根', color: '#5A4A3A', hardness: 0.0, transparent: true, category: 'natural' },
  { id: 'minecraft:small_dripleaf', name: 'Small Dripleaf', nameZh: '小型垂滴叶', color: '#5A8A4A', hardness: 0.0, transparent: false, category: 'natural' },
  { id: 'minecraft:big_dripleaf', name: 'Big Dripleaf', nameZh: '大型垂滴叶', color: '#5A8A4A', hardness: 0.0, transparent: false, category: 'natural' },
  { id: 'minecraft:moss_carpet', name: 'Moss Carpet', nameZh: '苔藓地毯', color: '#5A7A4A', hardness: 0.1, transparent: true, category: 'natural' },
  { id: 'minecraft:sugar_cane', name: 'Sugar Cane', nameZh: '甘蔗', color: '#8AAA5A', hardness: 0.0, transparent: true, category: 'natural' },
  { id: 'minecraft:bamboo', name: 'Bamboo', nameZh: '竹子', color: '#A4B040', hardness: 0.0, transparent: true, category: 'natural' },
  { id: 'minecraft:cactus', name: 'Cactus', nameZh: '仙人掌', color: '#4A8A4A', hardness: 0.4, transparent: true, category: 'natural' },
  { id: 'minecraft:lily_pad', name: 'Lily Pad', nameZh: '睡莲', color: '#4A8A4A', hardness: 0.0, transparent: true, category: 'natural' },
  { id: 'minecraft:spore_blossom', name: 'Spore Blossom', nameZh: '孢子花', color: '#A4D4A4', hardness: 0.0, transparent: true, category: 'natural' },
  { id: 'minecraft:cave_vines', name: 'Cave Vines', nameZh: '洞穴藤蔓', color: '#4A8A4A', hardness: 0.0, transparent: true, category: 'natural' },
  { id: 'minecraft:cave_vines_plant', name: 'Cave Vines Plant', nameZh: '洞穴藤蔓植物', color: '#4A8A4A', hardness: 0.0, transparent: true, category: 'natural' },
  { id: 'minecraft:glow_lichen', name: 'Glow Lichen', nameZh: '发光地衣', color: '#7AC47A', hardness: 0.0, transparent: true, category: 'natural' },
  { id: 'minecraft:lily_pad', name: 'Lily Pad', nameZh: '睡莲叶', color: '#4A8A4A', hardness: 0.0, transparent: true, category: 'natural' },

  // ========== 红石方块 ==========
  { id: 'minecraft:redstone_block', name: 'Block of Redstone', nameZh: '红石块', color: '#B80000', hardness: 5.0, transparent: false, category: 'redstone' },
  { id: 'minecraft:redstone_wire', name: 'Redstone Wire', nameZh: '红石粉', color: '#FF0000', hardness: 0.0, transparent: true, category: 'redstone' },
  { id: 'minecraft:redstone_torch', name: 'Redstone Torch', nameZh: '红石火把', color: '#FF6600', hardness: 0.0, transparent: true, category: 'redstone' },
  { id: 'minecraft:redstone_wall_torch', name: 'Redstone Wall Torch', nameZh: '墙壁红石火把', color: '#FF6600', hardness: 0.0, transparent: true, category: 'redstone' },
  { id: 'minecraft:repeater', name: 'Repeater', nameZh: '中继器', color: '#8B8B8B', hardness: 0.0, transparent: true, category: 'redstone' },
  { id: 'minecraft:comparator', name: 'Comparator', nameZh: '比较器', color: '#8B8B8B', hardness: 0.0, transparent: true, category: 'redstone' },
  { id: 'minecraft:lever', name: 'Lever', nameZh: '拉杆', color: '#808080', hardness: 0.5, transparent: true, category: 'redstone' },
  { id: 'minecraft:stone_button', name: 'Stone Button', nameZh: '石头按钮', color: '#909090', hardness: 0.5, transparent: true, category: 'redstone' },
  { id: 'minecraft:oak_button', name: 'Oak Button', nameZh: '木质按钮', color: '#BC9862', hardness: 0.5, transparent: true, category: 'redstone' },
  { id: 'minecraft:piston', name: 'Piston', nameZh: '活塞', color: '#9B9B9B', hardness: 1.5, transparent: false, category: 'redstone' },
  { id: 'minecraft:sticky_piston', name: 'Sticky Piston', nameZh: '粘性活塞', color: '#5D8C3E', hardness: 1.5, transparent: false, category: 'redstone' },
  { id: 'minecraft:observer', name: 'Observer', nameZh: '侦测器', color: '#6B6B6B', hardness: 3.5, transparent: false, category: 'redstone' },
  { id: 'minecraft:hopper', name: 'Hopper', nameZh: '漏斗', color: '#6B6B6B', hardness: 3, transparent: false, category: 'redstone' },
  { id: 'minecraft:dropper', name: 'Dropper', nameZh: '投掷器', color: '#8B8B8B', hardness: 3.5, transparent: false, category: 'redstone' },
  { id: 'minecraft:dispenser', name: 'Dispenser', nameZh: '发射器', color: '#8B8B8B', hardness: 3.5, transparent: false, category: 'redstone' },
  { id: 'minecraft:trapped_chest', name: 'Trapped Chest', nameZh: '陷阱箱', color: '#9B7B4B', hardness: 2.5, transparent: false, category: 'redstone' },
  { id: 'minecraft:daylight_detector', name: 'Daylight Detector', nameZh: '阳光探测器', color: '#D4C59E', hardness: 0.2, transparent: false, category: 'redstone' },
  { id: 'minecraft:heavy_weighted_pressure_plate', name: 'Heavy Weighted Pressure Plate', nameZh: '重质压力板', color: '#E8E8E8', hardness: 5.0, transparent: true, category: 'redstone' },
  { id: 'minecraft:light_weighted_pressure_plate', name: 'Light Weighted Pressure Plate', nameZh: '轻质压力板', color: '#FFAA00', hardness: 0.5, transparent: true, category: 'redstone' },
  { id: 'minecraft:stone_pressure_plate', name: 'Stone Pressure Plate', nameZh: '石质压力板', color: '#909090', hardness: 0.5, transparent: true, category: 'redstone' },
  { id: 'minecraft:oak_pressure_plate', name: 'Oak Pressure Plate', nameZh: '木质压力板', color: '#BC9862', hardness: 0.5, transparent: true, category: 'redstone' },
  { id: 'minecraft:tripwire_hook', name: 'Tripwire Hook', nameZh: '绊线钩', color: '#BC9862', hardness: 0.0, transparent: true, category: 'redstone' },
  { id: 'minecraft:powered_rail', name: 'Powered Rail', nameZh: '充能铁轨', color: '#8B8B8B', hardness: 0.7, transparent: true, category: 'redstone' },
  { id: 'minecraft:detector_rail', name: 'Detector Rail', nameZh: '探测铁轨', color: '#8B8B8B', hardness: 0.7, transparent: true, category: 'redstone' },
  { id: 'minecraft:activator_rail', name: 'Activator Rail', nameZh: '激活铁轨', color: '#8B8B8B', hardness: 0.7, transparent: true, category: 'redstone' },
  { id: 'minecraft:iron_trapdoor', name: 'Iron Trapdoor', nameZh: '铁活板门', color: '#E8E8E8', hardness: 5.0, transparent: true, category: 'redstone' },
  { id: 'minecraft:tripwire', name: 'Tripwire', nameZh: '绊线', color: '#D4C59E', hardness: 0.0, transparent: true, category: 'redstone' },
  { id: 'minecraft:slime_block', name: 'Slime Block', nameZh: '史莱姆方块', color: '#7FCC19', hardness: 0.0, transparent: false, category: 'redstone' },
  { id: 'minecraft:honey_block', name: 'Honey Block', nameZh: '蜂蜜块', color: '#E4A128', hardness: 0.0, transparent: false, category: 'redstone' },
  { id: 'minecraft:target', name: 'Target', nameZh: '标靶', color: '#CC3333', hardness: 0.5, transparent: false, category: 'redstone' },
  { id: 'minecraft:sculk_sensor', name: 'Sculk Sensor', nameZh: '幽匿传感器', color: '#1A5F5F', hardness: 1.8, transparent: false, category: 'redstone' },
  { id: 'minecraft:sculk_catalyst', name: 'Sculk Catalyst', nameZh: '幽匿催发体', color: '#1A4F4F', hardness: 1.8, transparent: false, category: 'redstone' },
  { id: 'minecraft:sculk_shrieker', name: 'Sculk Shrieker', nameZh: '幽匿哀嚎者', color: '#1A3F3F', hardness: 1.8, transparent: false, category: 'redstone' },
  { id: 'minecraft:lightning_rod', name: 'Lightning Rod', nameZh: '避雷针', color: '#D4A574', hardness: 3.0, transparent: true, category: 'redstone' },
  { id: 'minecraft:note_block', name: 'Note Block', nameZh: '音符盒', color: '#BC9862', hardness: 0.8, transparent: false, category: 'redstone' },
  { id: 'minecraft:tnt', name: 'TNT', nameZh: 'TNT', color: '#CC3333', hardness: 0.0, transparent: true, category: 'redstone' },

  // ========== 装饰方块 ==========
  { id: 'minecraft:oak_stairs', name: 'Oak Stairs', nameZh: '橡木楼梯', color: '#BC9862', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:spruce_stairs', name: 'Spruce Stairs', nameZh: '云杉楼梯', color: '#6B5430', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:birch_stairs', name: 'Birch Stairs', nameZh: '桦木楼梯', color: '#D4C59E', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:jungle_stairs', name: 'Jungle Stairs', nameZh: '丛林楼梯', color: '#9B7B5A', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:acacia_stairs', name: 'Acacia Stairs', nameZh: '金合欢楼梯', color: '#A45A3A', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:dark_oak_stairs', name: 'Dark Oak Stairs', nameZh: '深色橡木楼梯', color: '#4A3728', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:mangrove_stairs', name: 'Mangrove Stairs', nameZh: '红树楼梯', color: '#6B4A3A', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:cherry_stairs', name: 'Cherry Stairs', nameZh: '樱花楼梯', color: '#D4A0A0', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:bamboo_stairs', name: 'Bamboo Stairs', nameZh: '竹楼梯', color: '#B5A040', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:bamboo_mosaic_stairs', name: 'Bamboo Mosaic Stairs', nameZh: '竹马赛克楼梯', color: '#C5B050', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:crimson_stairs', name: 'Crimson Stairs', nameZh: '绯红楼梯', color: '#8B3A4A', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:warped_stairs', name: 'Warped Stairs', nameZh: '扭曲楼梯', color: '#3A8B7B', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:stone_stairs', name: 'Stone Stairs', nameZh: '石楼梯', color: '#808080', hardness: 1.5, transparent: false, category: 'decoration' },
  { id: 'minecraft:cobblestone_stairs', name: 'Cobblestone Stairs', nameZh: '圆石楼梯', color: '#6B6B6B', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:mossy_cobblestone_stairs', name: 'Mossy Cobblestone Stairs', nameZh: '苔圆石楼梯', color: '#5A6B5A', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:sandstone_stairs', name: 'Sandstone Stairs', nameZh: '砂岩楼梯', color: '#E8D4A8', hardness: 0.8, transparent: false, category: 'decoration' },
  { id: 'minecraft:red_sandstone_stairs', name: 'Red Sandstone Stairs', nameZh: '红砂岩楼梯', color: '#D47A3A', hardness: 0.8, transparent: false, category: 'decoration' },
  { id: 'minecraft:prismarine_stairs', name: 'Prismarine Stairs', nameZh: '海晶石楼梯', color: '#4A8B7A', hardness: 1.5, transparent: false, category: 'decoration' },
  { id: 'minecraft:prismarine_brick_stairs', name: 'Prismarine Brick Stairs', nameZh: '海晶砖楼梯', color: '#5A9B8A', hardness: 1.5, transparent: false, category: 'decoration' },
  { id: 'minecraft:dark_prismarine_stairs', name: 'Dark Prismarine Stairs', nameZh: '暗海晶石楼梯', color: '#2A5B4A', hardness: 1.5, transparent: false, category: 'decoration' },
  { id: 'minecraft:nether_brick_stairs', name: 'Nether Brick Stairs', nameZh: '下界砖楼梯', color: '#2A1A1A', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:red_nether_brick_stairs', name: 'Red Nether Brick Stairs', nameZh: '红色下界砖楼梯', color: '#5A1A1A', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:end_stone_brick_stairs', name: 'End Stone Brick Stairs', nameZh: '末地石砖楼梯', color: '#E8E8CC', hardness: 3.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:quartz_stairs', name: 'Quartz Stairs', nameZh: '石英楼梯', color: '#E8E8E8', hardness: 0.8, transparent: false, category: 'decoration' },
  { id: 'minecraft:purpur_stairs', name: 'Purpur Stairs', nameZh: '紫珀楼梯', color: '#9B7BBF', hardness: 1.5, transparent: false, category: 'decoration' },
  { id: 'minecraft:deepslate_stairs', name: 'Deepslate Stairs', nameZh: '深板岩楼梯', color: '#3D3D4A', hardness: 3.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:cobbled_deepslate_stairs', name: 'Cobbled Deepslate Stairs', nameZh: '深板岩圆石楼梯', color: '#4A4A5A', hardness: 3.5, transparent: false, category: 'decoration' },
  { id: 'minecraft:polished_deepslate_stairs', name: 'Polished Deepslate Stairs', nameZh: '磨制深板岩楼梯', color: '#4D4D5A', hardness: 3.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:polished_blackstone_stairs', name: 'Polished Blackstone Stairs', nameZh: '磨制黑石楼梯', color: '#2A2A2A', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:polished_blackstone_brick_stairs', name: 'Polished Blackstone Brick Stairs', nameZh: '磨制黑石砖楼梯', color: '#2A2A2A', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:blackstone_stairs', name: 'Blackstone Stairs', nameZh: '黑石楼梯', color: '#1a1a1a', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:oak_slab', name: 'Oak Slab', nameZh: '橡木台阶', color: '#BC9862', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:spruce_slab', name: 'Spruce Slab', nameZh: '云杉台阶', color: '#6B5430', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:birch_slab', name: 'Birch Slab', nameZh: '桦木台阶', color: '#D4C59E', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:jungle_slab', name: 'Jungle Slab', nameZh: '丛林台阶', color: '#9B7B5A', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:acacia_slab', name: 'Acacia Slab', nameZh: '金合欢台阶', color: '#A45A3A', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:dark_oak_slab', name: 'Dark Oak Slab', nameZh: '深色橡木台阶', color: '#4A3728', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:mangrove_slab', name: 'Mangrove Slab', nameZh: '红树台阶', color: '#6B4A3A', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:cherry_slab', name: 'Cherry Slab', nameZh: '樱花台阶', color: '#D4A0A0', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:bamboo_slab', name: 'Bamboo Slab', nameZh: '竹台阶', color: '#B5A040', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:bamboo_mosaic_slab', name: 'Bamboo Mosaic Slab', nameZh: '竹马赛克台阶', color: '#C5B050', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:crimson_slab', name: 'Crimson Slab', nameZh: '绯红台阶', color: '#8B3A4A', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:warped_slab', name: 'Warped Slab', nameZh: '扭曲台阶', color: '#3A8B7B', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:stone_slab', name: 'Stone Slab', nameZh: '石台阶', color: '#808080', hardness: 1.5, transparent: true, category: 'decoration' },
  { id: 'minecraft:cobblestone_slab', name: 'Cobblestone Slab', nameZh: '圆石台阶', color: '#6B6B6B', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:mossy_cobblestone_slab', name: 'Mossy Cobblestone Slab', nameZh: '苔圆石台阶', color: '#5A6B5A', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:sandstone_slab', name: 'Sandstone Slab', nameZh: '砂岩台阶', color: '#E8D4A8', hardness: 0.8, transparent: true, category: 'decoration' },
  { id: 'minecraft:cut_sandstone_slab', name: 'Cut Sandstone Slab', nameZh: '切制砂岩台阶', color: '#E8D4A8', hardness: 0.8, transparent: true, category: 'decoration' },
  { id: 'minecraft:red_sandstone_slab', name: 'Red Sandstone Slab', nameZh: '红砂岩台阶', color: '#D47A3A', hardness: 0.8, transparent: true, category: 'decoration' },
  { id: 'minecraft:cut_red_sandstone_slab', name: 'Cut Red Sandstone Slab', nameZh: '切制红砂岩台阶', color: '#D47A3A', hardness: 0.8, transparent: true, category: 'decoration' },
  { id: 'minecraft:prismarine_slab', name: 'Prismarine Slab', nameZh: '海晶石台阶', color: '#4A8B7A', hardness: 1.5, transparent: true, category: 'decoration' },
  { id: 'minecraft:prismarine_brick_slab', name: 'Prismarine Brick Slab', nameZh: '海晶砖台阶', color: '#5A9B8A', hardness: 1.5, transparent: true, category: 'decoration' },
  { id: 'minecraft:dark_prismarine_slab', name: 'Dark Prismarine Slab', nameZh: '暗海晶石台阶', color: '#2A5B4A', hardness: 1.5, transparent: true, category: 'decoration' },
  { id: 'minecraft:nether_brick_slab', name: 'Nether Brick Slab', nameZh: '下界砖台阶', color: '#2A1A1A', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:quartz_slab', name: 'Quartz Slab', nameZh: '石英台阶', color: '#E8E8E8', hardness: 0.8, transparent: true, category: 'decoration' },
  { id: 'minecraft:smooth_quartz_slab', name: 'Smooth Quartz Slab', nameZh: '平滑石英台阶', color: '#E8E8E8', hardness: 0.8, transparent: true, category: 'decoration' },
  { id: 'minecraft:purpur_slab', name: 'Purpur Slab', nameZh: '紫珀台阶', color: '#9B7BBF', hardness: 1.5, transparent: true, category: 'decoration' },
  { id: 'minecraft:end_stone_brick_slab', name: 'End Stone Brick Slab', nameZh: '末地石砖台阶', color: '#E8E8CC', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:smooth_stone_slab', name: 'Smooth Stone Slab', nameZh: '平滑石台阶', color: '#909090', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:deepslate_slab', name: 'Deepslate Slab', nameZh: '深板岩台阶', color: '#3D3D4A', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:cobbled_deepslate_slab', name: 'Cobbled Deepslate Slab', nameZh: '深板岩圆石台阶', color: '#4A4A5A', hardness: 3.5, transparent: true, category: 'decoration' },
  { id: 'minecraft:polished_deepslate_slab', name: 'Polished Deepslate Slab', nameZh: '磨制深板岩台阶', color: '#4D4D5A', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:polished_blackstone_slab', name: 'Polished Blackstone Slab', nameZh: '磨制黑石台阶', color: '#2A2A2A', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:polished_blackstone_brick_slab', name: 'Polished Blackstone Brick Slab', nameZh: '磨制黑石砖台阶', color: '#2A2A2A', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:oak_door', name: 'Oak Door', nameZh: '橡木门', color: '#BC9862', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:spruce_door', name: 'Spruce Door', nameZh: '云杉门', color: '#6B5430', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:birch_door', name: 'Birch Door', nameZh: '桦木门', color: '#D4C59E', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:jungle_door', name: 'Jungle Door', nameZh: '丛林门', color: '#9B7B5A', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:acacia_door', name: 'Acacia Door', nameZh: '金合欢门', color: '#A45A3A', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:dark_oak_door', name: 'Dark Oak Door', nameZh: '深色橡木门', color: '#4A3728', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:mangrove_door', name: 'Mangrove Door', nameZh: '红树门', color: '#6B4A3A', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:cherry_door', name: 'Cherry Door', nameZh: '樱花门', color: '#D4A0A0', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:bamboo_door', name: 'Bamboo Door', nameZh: '竹门', color: '#B5A040', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:crimson_door', name: 'Crimson Door', nameZh: '绯红门', color: '#8B3A4A', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:warped_door', name: 'Warped Door', nameZh: '扭曲门', color: '#3A8B7B', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:iron_door', name: 'Iron Door', nameZh: '铁门', color: '#E8E8E8', hardness: 5.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:oak_trapdoor', name: 'Oak Trapdoor', nameZh: '橡木活板门', color: '#BC9862', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:spruce_trapdoor', name: 'Spruce Trapdoor', nameZh: '云杉活板门', color: '#6B5430', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:birch_trapdoor', name: 'Birch Trapdoor', nameZh: '桦木活板门', color: '#D4C59E', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:jungle_trapdoor', name: 'Jungle Trapdoor', nameZh: '丛林活板门', color: '#9B7B5A', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:acacia_trapdoor', name: 'Acacia Trapdoor', nameZh: '金合欢活板门', color: '#A45A3A', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:dark_oak_trapdoor', name: 'Dark Oak Trapdoor', nameZh: '深色橡木活板门', color: '#4A3728', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:mangrove_trapdoor', name: 'Mangrove Trapdoor', nameZh: '红树活板门', color: '#6B4A3A', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:cherry_trapdoor', name: 'Cherry Trapdoor', nameZh: '樱花活板门', color: '#D4A0A0', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:bamboo_trapdoor', name: 'Bamboo Trapdoor', nameZh: '竹活板门', color: '#B5A040', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:crimson_trapdoor', name: 'Crimson Trapdoor', nameZh: '绯红活板门', color: '#8B3A4A', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:warped_trapdoor', name: 'Warped Trapdoor', nameZh: '扭曲活板门', color: '#3A8B7B', hardness: 3.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:fence', name: 'Oak Fence', nameZh: '橡木栅栏', color: '#BC9862', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:spruce_fence', name: 'Spruce Fence', nameZh: '云杉栅栏', color: '#6B5430', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:birch_fence', name: 'Birch Fence', nameZh: '桦木栅栏', color: '#D4C59E', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:jungle_fence', name: 'Jungle Fence', nameZh: '丛林栅栏', color: '#9B7B5A', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:acacia_fence', name: 'Acacia Fence', nameZh: '金合欢栅栏', color: '#A45A3A', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:dark_oak_fence', name: 'Dark Oak Fence', nameZh: '深色橡木栅栏', color: '#4A3728', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:nether_brick_fence', name: 'Nether Brick Fence', nameZh: '下界砖栅栏', color: '#2A1A1A', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:fence_gate', name: 'Oak Fence Gate', nameZh: '橡木栅栏门', color: '#BC9862', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:spruce_fence_gate', name: 'Spruce Fence Gate', nameZh: '云杉栅栏门', color: '#6B5430', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:birch_fence_gate', name: 'Birch Fence Gate', nameZh: '桦木栅栏门', color: '#D4C59E', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:jungle_fence_gate', name: 'Jungle Fence Gate', nameZh: '丛林栅栏门', color: '#9B7B5A', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:acacia_fence_gate', name: 'Acacia Fence Gate', nameZh: '金合欢栅栏门', color: '#A45A3A', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:dark_oak_fence_gate', name: 'Dark Oak Fence Gate', nameZh: '深色橡木栅栏门', color: '#4A3728', hardness: 2.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:wall_sign', name: 'Wall Sign', nameZh: '墙壁告示牌', color: '#BC9862', hardness: 1.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:oak_sign', name: 'Oak Sign', nameZh: '橡木告示牌', color: '#BC9862', hardness: 1.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:spruce_sign', name: 'Spruce Sign', nameZh: '云杉告示牌', color: '#6B5430', hardness: 1.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:birch_sign', name: 'Birch Sign', nameZh: '桦木告示牌', color: '#D4C59E', hardness: 1.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:jungle_sign', name: 'Jungle Sign', nameZh: '丛林告示牌', color: '#9B7B5A', hardness: 1.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:acacia_sign', name: 'Acacia Sign', nameZh: '金合欢告示牌', color: '#A45A3A', hardness: 1.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:dark_oak_sign', name: 'Dark Oak Sign', nameZh: '深色橡木告示牌', color: '#4A3728', hardness: 1.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:mangrove_sign', name: 'Mangrove Sign', nameZh: '红树告示牌', color: '#6B4A3A', hardness: 1.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:cherry_sign', name: 'Cherry Sign', nameZh: '樱花告示牌', color: '#D4A0A0', hardness: 1.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:bamboo_sign', name: 'Bamboo Sign', nameZh: '竹告示牌', color: '#B5A040', hardness: 1.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:crimson_sign', name: 'Crimson Sign', nameZh: '绯红告示牌', color: '#8B3A4A', hardness: 1.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:warped_sign', name: 'Warped Sign', nameZh: '扭曲告示牌', color: '#3A8B7B', hardness: 1.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:painting', name: 'Painting', nameZh: '画', color: '#D4A03A', hardness: 0.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:item_frame', name: 'Item Frame', nameZh: '物品展示框', color: '#8B6B4B', hardness: 0.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:glow_item_frame', name: 'Glow Item Frame', nameZh: '发光物品展示框', color: '#8B6B4B', hardness: 0.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:flower_pot', name: 'Flower Pot', nameZh: '花盆', color: '#9B5B4A', hardness: 0.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:armor_stand', name: 'Armor Stand', nameZh: '盔甲架', color: '#8B6B4B', hardness: 0.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:torch', name: 'Torch', nameZh: '火把', color: '#FFAA00', hardness: 0.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:soul_torch', name: 'Soul Torch', nameZh: '灵魂火把', color: '#6699CC', hardness: 0.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:wall_torch', name: 'Wall Torch', nameZh: '墙壁火把', color: '#FFAA00', hardness: 0.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:ladder', name: 'Ladder', nameZh: '梯子', color: '#BC9862', hardness: 0.4, transparent: true, category: 'decoration' },
  { id: 'minecraft:chain', name: 'Chain', nameZh: '锁链', color: '#505050', hardness: 3, transparent: true, category: 'decoration' },
  { id: 'minecraft:bell', name: 'Bell', nameZh: '钟', color: '#FFAA00', hardness: 5.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:lantern', name: 'Lantern', nameZh: '灯笼', color: '#FFAA00', hardness: 0.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:soul_lantern', name: 'Soul Lantern', nameZh: '灵魂灯笼', color: '#6699CC', hardness: 0.0, transparent: true, category: 'decoration' },
  { id: 'minecraft:respawn_anchor', name: 'Respawn Anchor', nameZh: '重生锚', color: '#4A1A6A', hardness: 3.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:lodestone', name: 'Lodestone', nameZh: '磁石', color: '#6B6B7A', hardness: 3.5, transparent: false, category: 'decoration' },
  { id: 'minecraft:cartography_table', name: 'Cartography Table', nameZh: '制图台', color: '#8B6B4B', hardness: 2.5, transparent: false, category: 'decoration' },
  { id: 'minecraft:fletching_table', name: 'Fletching Table', nameZh: '制箭台', color: '#8B6B4B', hardness: 2.5, transparent: false, category: 'decoration' },
  { id: 'minecraft:smithing_table', name: 'Smithing Table', nameZh: '锻造台', color: '#8B6B4B', hardness: 2.5, transparent: false, category: 'decoration' },
  { id: 'minecraft:brewING_stand', name: 'Brewing Stand', nameZh: '酿造台', color: '#4A3A3A', hardness: 0.5, transparent: false, category: 'decoration' },
  { id: 'minecraft:enchanting_table', name: 'Enchanting Table', nameZh: '附魔台', color: '#1A1A4A', hardness: 3.5, transparent: false, category: 'decoration' },
  { id: 'minecraft:anvil', name: 'Anvil', nameZh: '铁砧', color: '#5A5A6A', hardness: 5.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:chipped_anvil', name: 'Chipped Anvil', nameZh: '损坏铁砧', color: '#5A5A6A', hardness: 5.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:damaged_anvil', name: 'Damaged Anvil', nameZh: '严重损坏铁砧', color: '#5A5A6A', hardness: 5.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:grindstone', name: 'Grindstone', nameZh: '砂轮', color: '#8B8B8B', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:stonecutter', name: 'Stonecutter', nameZh: '切石机', color: '#8B8B8B', hardness: 3.5, transparent: false, category: 'decoration' },
  { id: 'minecraft:loom', name: 'Loom', nameZh: '织布机', color: '#8B6B4B', hardness: 2.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:lectern', name: 'Lectern', nameZh: '讲台', color: '#BC9862', hardness: 2.5, transparent: false, category: 'decoration' },
  { id: 'minecraft:composter', name: 'Composter', nameZh: '堆肥桶', color: '#8B6B4B', hardness: 0.6, transparent: false, category: 'decoration' },
  { id: 'minecraft:beehive', name: 'Beehive', nameZh: '蜂箱', color: '#D4A528', hardness: 0.6, transparent: false, category: 'decoration' },
  { id: 'minecraft:bee_nest', name: 'Bee Nest', nameZh: '蜜蜂巢', color: '#D4A528', hardness: 0.6, transparent: false, category: 'decoration' },
  { id: 'minecraft:honeycomb_block', name: 'Honeycomb Block', nameZh: '蜜脾块', color: '#DDA62B', hardness: 0.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:honey_block', name: 'Honey Block', nameZh: '蜂蜜块', color: '#E4A128', hardness: 0.0, transparent: false, category: 'decoration' },
  { id: 'minecraft:chorus_plant', name: 'Chorus Plant', nameZh: '紫颂植物', color: '#7A5A8A', hardness: 0.4, transparent: true, category: 'decoration' },
  { id: 'minecraft:chorus_flower', name: 'Chorus Flower', nameZh: '紫颂花', color: '#9A7AAA', hardness: 0.4, transparent: false, category: 'decoration' },

  // ========== 功能方块 ==========
  { id: 'minecraft:crafting_table', name: 'Crafting Table', nameZh: '工作台', color: '#BC9862', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:furnace', name: 'Furnace', nameZh: '熔炉', color: '#808080', hardness: 3.5, transparent: false, category: 'utility' },
  { id: 'minecraft:blast_furnace', name: 'Blast Furnace', nameZh: '高炉', color: '#606060', hardness: 3.5, transparent: false, category: 'utility' },
  { id: 'minecraft:smoker', name: 'Smoker', nameZh: '烟熏炉', color: '#8B5A3C', hardness: 3.5, transparent: false, category: 'utility' },
  { id: 'minecraft:cartography_table', name: 'Cartography Table', nameZh: '制图台', color: '#8B6B4B', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:fletching_table', name: 'Fletching Table', nameZh: '制箭台', color: '#8B6B4B', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:smithing_table', name: 'Smithing Table', nameZh: '锻造台', color: '#8B6B4B', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:enchanting_table', name: 'Enchanting Table', nameZh: '附魔台', color: '#1A1A4A', hardness: 3.5, transparent: false, category: 'utility' },
  { id: 'minecraft:anvil', name: 'Anvil', nameZh: '铁砧', color: '#5A5A6A', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:grindstone', name: 'Grindstone', nameZh: '砂轮', color: '#8B8B8B', hardness: 2.0, transparent: false, category: 'utility' },
  { id: 'minecraft:stonecutter', name: 'Stonecutter', nameZh: '切石机', color: '#8B8B8B', hardness: 3.5, transparent: false, category: 'utility' },
  { id: 'minecraft:loom', name: 'Loom', nameZh: '织布机', color: '#8B6B4B', hardness: 2.0, transparent: false, category: 'utility' },
  { id: 'minecraft:lectern', name: 'Lectern', nameZh: '讲台', color: '#BC9862', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:brewing_stand', name: 'Brewing Stand', nameZh: '酿造台', color: '#4A3A3A', hardness: 0.5, transparent: false, category: 'utility' },
  { id: 'minecraft:cauldron', name: 'Cauldron', nameZh: '炼药锅', color: '#4A4A5A', hardness: 2.0, transparent: false, category: 'utility' },
  { id: 'minecraft:water_cauldron', name: 'Water Cauldron', nameZh: '水炼药锅', color: '#4A6A9A', hardness: 2.0, transparent: false, category: 'utility' },
  { id: 'minecraft:lava_cauldron', name: 'Lava Cauldron', nameZh: '岩浆炼药锅', color: '#9A4A1A', hardness: 2.0, transparent: false, category: 'utility' },
  { id: 'minecraft:powder_cauldron', name: 'Powder Cauldron', nameZh: '粉末炼药锅', color: '#AAA9A9', hardness: 2.0, transparent: false, category: 'utility' },
  { id: 'minecraft:chest', name: 'Chest', nameZh: '箱子', color: '#BC9862', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:ender_chest', name: 'Ender Chest', nameZh: '末影箱', color: '#2A2A4A', hardness: 22.5, transparent: false, category: 'utility' },
  { id: 'minecraft:trapped_chest', name: 'Trapped Chest', nameZh: '陷阱箱', color: '#9B7B4B', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:barrel', name: 'Barrel', nameZh: '木桶', color: '#8B6B4B', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:shulker_box', name: 'Shulker Box', nameZh: '潜影盒', color: '#9B7BBF', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:white_shulker_box', name: 'White Shulker Box', nameZh: '白色潜影盒', color: '#E8E8E8', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:orange_shulker_box', name: 'Orange Shulker Box', nameZh: '橙色潜影盒', color: '#E57A1A', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:magenta_shulker_box', name: 'Magenta Shulker Box', nameZh: '品红潜影盒', color: '#B41AB4', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:light_blue_shulker_box', name: 'Light Blue Shulker Box', nameZh: '淡蓝色潜影盒', color: '#4A9AD4', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:yellow_shulker_box', name: 'Yellow Shulker Box', nameZh: '黄色潜影盒', color: '#E8D41A', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:lime_shulker_box', name: 'Lime Shulker Box', nameZh: '黄绿色潜影盒', color: '#7AC41A', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:pink_shulker_box', name: 'Pink Shulker Box', nameZh: '粉色潜影盒', color: '#D49AC4', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:gray_shulker_box', name: 'Gray Shulker Box', nameZh: '灰色潜影盒', color: '#4A4A4A', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:light_gray_shulker_box', name: 'Light Gray Shulker Box', nameZh: '淡灰色潜影盒', color: '#9A9A9A', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:cyan_shulker_box', name: 'Cyan Shulker Box', nameZh: '青色潜影盒', color: '#1A9A9A', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:purple_shulker_box', name: 'Purple Shulker Box', nameZh: '紫色潜影盒', color: '#6A1A9A', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:blue_shulker_box', name: 'Blue Shulker Box', nameZh: '蓝色潜影盒', color: '#1A1A9A', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:brown_shulker_box', name: 'Brown Shulker Box', nameZh: '棕色潜影盒', color: '#6B4A2A', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:green_shulker_box', name: 'Green Shulker Box', nameZh: '绿色潜影盒', color: '#4A8A1A', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:red_shulker_box', name: 'Red Shulker Box', nameZh: '红色潜影盒', color: '#9A1A1A', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:black_shulker_box', name: 'Black Shulker Box', nameZh: '黑色潜影盒', color: '#1A1A1A', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:hopper', name: 'Hopper', nameZh: '漏斗', color: '#6B6B6B', hardness: 3, transparent: false, category: 'utility' },
  { id: 'minecraft:dropper', name: 'Dropper', nameZh: '投掷器', color: '#8B8B8B', hardness: 3.5, transparent: false, category: 'utility' },
  { id: 'minecraft:dispenser', name: 'Dispenser', nameZh: '发射器', color: '#8B8B8B', hardness: 3.5, transparent: false, category: 'utility' },
  { id: 'minecraft:lever', name: 'Lever', nameZh: '拉杆', color: '#808080', hardness: 0.5, transparent: true, category: 'utility' },
  { id: 'minecraft:stone_button', name: 'Stone Button', nameZh: '石头按钮', color: '#909090', hardness: 0.5, transparent: true, category: 'utility' },
  { id: 'minecraft:oak_button', name: 'Oak Button', nameZh: '木质按钮', color: '#BC9862', hardness: 0.5, transparent: true, category: 'utility' },
  { id: 'minecraft:heavy_weighted_pressure_plate', name: 'Heavy Weighted Pressure Plate', nameZh: '重质压力板', color: '#E8E8E8', hardness: 5.0, transparent: true, category: 'utility' },
  { id: 'minecraft:light_weighted_pressure_plate', name: 'Light Weighted Pressure Plate', nameZh: '轻质压力板', color: '#FFAA00', hardness: 0.5, transparent: true, category: 'utility' },
  { id: 'minecraft:stone_pressure_plate', name: 'Stone Pressure Plate', nameZh: '石质压力板', color: '#909090', hardness: 0.5, transparent: true, category: 'utility' },
  { id: 'minecraft:oak_pressure_plate', name: 'Oak Pressure Plate', nameZh: '木质压力板', color: '#BC9862', hardness: 0.5, transparent: true, category: 'utility' },
  { id: 'minecraft:daylight_detector', name: 'Daylight Detector', nameZh: '阳光探测器', color: '#D4C59E', hardness: 0.2, transparent: false, category: 'utility' },
  { id: 'minecraft:calibrated_sculk_sensor', name: 'Calibrated Sculk Sensor', nameZh: '校准幽匿传感器', color: '#1A5F5F', hardness: 1.8, transparent: false, category: 'utility' },
  { id: 'minecraft:sculk_shrieker', name: 'Sculk Shrieker', nameZh: '幽匿哀嚎者', color: '#1A3F3F', hardness: 1.8, transparent: false, category: 'utility' },
  { id: 'minecraft:sculk_catalyst', name: 'Sculk Catalyst', nameZh: '幽匿催发体', color: '#1A4F4F', hardness: 1.8, transparent: false, category: 'utility' },
  { id: 'minecraft:jukebox', name: 'Jukebox', nameZh: '唱片机', color: '#BC9862', hardness: 2.0, transparent: false, category: 'utility' },
  { id: 'minecraft:beehive', name: 'Beehive', nameZh: '蜂箱', color: '#D4A528', hardness: 0.6, transparent: false, category: 'utility' },
  { id: 'minecraft:bee_nest', name: 'Bee Nest', nameZh: '蜜蜂巢', color: '#D4A528', hardness: 0.6, transparent: false, category: 'utility' },
  { id: 'minecraft:composter', name: 'Composter', nameZh: '堆肥桶', color: '#8B6B4B', hardness: 0.6, transparent: false, category: 'utility' },
  { id: 'minecraft:lightning_rod', name: 'Lightning Rod', nameZh: '避雷针', color: '#D4A574', hardness: 3.0, transparent: true, category: 'utility' },
  { id: 'minecraft:soul_campfire', name: 'Soul Campfire', nameZh: '灵魂营火', color: '#6699CC', hardness: 0.0, transparent: true, category: 'utility' },
  { id: 'minecraft:campfire', name: 'Campfire', nameZh: '营火', color: '#FFAA00', hardness: 0.0, transparent: true, category: 'utility' },
  { id: 'minecraft:blast_furnace', name: 'Blast Furnace', nameZh: '高炉', color: '#606060', hardness: 3.5, transparent: false, category: 'utility' },
  { id: 'minecraft:smoker', name: 'Smoker', nameZh: '烟熏炉', color: '#8B5A3C', hardness: 3.5, transparent: false, category: 'utility' },
  { id: 'minecraft:cartography_table', name: 'Cartography Table', nameZh: '制图台', color: '#8B6B4B', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:fletching_table', name: 'Fletching Table', nameZh: '制箭台', color: '#8B6B4B', hardness: 2.5, transparent: false, category: 'utility' },
  { id: 'minecraft:smithing_table', name: 'Smithing Table', nameZh: '锻造台', color: '#8B6B4B', hardness: 2.5, transparent: false, category: 'utility' },

  // ========== 矿物方块 ==========
  { id: 'minecraft:coal_block', name: 'Coal Block', nameZh: '煤炭块', color: '#1A1A1A', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:iron_block', name: 'Block of Iron', nameZh: '铁块', color: '#E8E8E8', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:gold_block', name: 'Block of Gold', nameZh: '金块', color: '#FFAA00', hardness: 3.0, transparent: false, category: 'utility' },
  { id: 'minecraft:diamond_block', name: 'Block of Diamond', nameZh: '钻石块', color: '#4AEDD9', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:netherite_block', name: 'Block of Netherite', nameZh: '下界合金块', color: '#4A4A52', hardness: 50, transparent: false, category: 'utility' },
  { id: 'minecraft:emerald_block', name: 'Block of Emerald', nameZh: '绿宝石块', color: '#50C878', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:lapis_block', name: 'Lapis Lazuli Block', nameZh: '青金石块', color: '#1E3A8A', hardness: 3.0, transparent: false, category: 'utility' },
  { id: 'minecraft:redstone_block', name: 'Block of Redstone', nameZh: '红石块', color: '#B80000', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:copper_block', name: 'Copper Block', nameZh: '铜块', color: '#B87850', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:exposed_copper', name: 'Exposed Copper', nameZh: '曝露铜块', color: '#9A6A40', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:weathered_copper', name: 'Weathered Copper', nameZh: '风化铜块', color: '#6A5A4A', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:oxidized_copper', name: 'Oxidized Copper', nameZh: '氧化铜块', color: '#4A5A5A', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:cut_copper', name: 'Cut Copper', nameZh: '切制铜块', color: '#B87850', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:exposed_cut_copper', name: 'Exposed Cut Copper', nameZh: '曝露切制铜块', color: '#9A6A40', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:weathered_cut_copper', name: 'Weathered Cut Copper', nameZh: '风化切制铜块', color: '#6A5A4A', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:oxidized_cut_copper', name: 'Oxidized Cut Copper', nameZh: '氧化切制铜块', color: '#4A5A5A', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:cut_copper_stairs', name: 'Cut Copper Stairs', nameZh: '切制铜楼梯', color: '#B87850', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:exposed_cut_copper_stairs', name: 'Exposed Cut Copper Stairs', nameZh: '曝露切制铜楼梯', color: '#9A6A40', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:weathered_cut_copper_stairs', name: 'Weathered Cut Copper Stairs', nameZh: '风化切制铜楼梯', color: '#6A5A4A', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:oxidized_cut_copper_stairs', name: 'Oxidized Cut Copper Stairs', nameZh: '氧化切制铜楼梯', color: '#4A5A5A', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:cut_copper_slab', name: 'Cut Copper Slab', nameZh: '切制铜台阶', color: '#B87850', hardness: 5.0, transparent: true, category: 'utility' },
  { id: 'minecraft:exposed_cut_copper_slab', name: 'Exposed Cut Copper Slab', nameZh: '曝露切制铜台阶', color: '#9A6A40', hardness: 5.0, transparent: true, category: 'utility' },
  { id: 'minecraft:weathered_cut_copper_slab', name: 'Weathered Cut Copper Slab', nameZh: '风化切制铜台阶', color: '#6A5A4A', hardness: 5.0, transparent: true, category: 'utility' },
  { id: 'minecraft:oxidized_cut_copper_slab', name: 'Oxidized Cut Copper Slab', nameZh: '氧化切制铜台阶', color: '#4A5A5A', hardness: 5.0, transparent: true, category: 'utility' },
  { id: 'minecraft:amethyst_block', name: 'Amethyst Block', nameZh: '紫水晶块', color: '#9966CC', hardness: 1.5, transparent: false, category: 'utility' },
  { id: 'minecraft:budding_amethyst', name: 'Budding Amethyst', nameZh: '萌芽紫水晶', color: '#8966BB', hardness: 1.5, transparent: false, category: 'utility' },
  { id: 'minecraft:iron_block', name: 'Iron Block', nameZh: '铁块', color: '#E8E8E8', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:raw_iron_block', name: 'Raw Iron Block', nameZh: '粗铁块', color: '#C8A888', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:raw_gold_block', name: 'Raw Gold Block', nameZh: '粗金块', color: '#D4B428', hardness: 3.0, transparent: false, category: 'utility' },
  { id: 'minecraft:raw_copper_block', name: 'Raw Copper Block', nameZh: '粗铜块', color: '#B87850', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:netherite_block', name: 'Netherite Block', nameZh: '下界合金块', color: '#4A4A52', hardness: 50, transparent: false, category: 'utility' },
  { id: 'minecraft:coal_block', name: 'Coal Block', nameZh: '煤炭块', color: '#1A1A1A', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:diamond_block', name: 'Diamond Block', nameZh: '钻石块', color: '#4AEDD9', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:emerald_block', name: 'Emerald Block', nameZh: '绿宝石块', color: '#50C878', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:lapis_block', name: 'Lapis Lazuli Block', nameZh: '青金石块', color: '#1E3A8A', hardness: 3.0, transparent: false, category: 'utility' },
  { id: 'minecraft:redstone_block', name: 'Redstone Block', nameZh: '红石块', color: '#B80000', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:gold_block', name: 'Gold Block', nameZh: '金块', color: '#FFAA00', hardness: 3.0, transparent: false, category: 'utility' },
  { id: 'minecraft:iron_block', name: 'Iron Block', nameZh: '铁块', color: '#E8E8E8', hardness: 5.0, transparent: false, category: 'utility' },
  { id: 'minecraft:nether_star_block', name: 'Nether Star Block', nameZh: '下界之星块', color: '#E8E8A8', hardness: 1.0, transparent: false, category: 'utility' },
  { id: 'minecraft:dragon_egg', name: 'Dragon Egg', nameZh: '龙蛋', color: '#1A1A2A', hardness: 3.0, transparent: false, category: 'utility' },
  { id: 'minecraft:beacon', name: 'Beacon', nameZh: '信标', color: '#7AD4E8', hardness: 3.0, transparent: false, category: 'utility' },
  { id: 'minecraft:conduit', name: 'Conduit', nameZh: '潮涌核心', color: '#6AC4D4', hardness: 3.0, transparent: false, category: 'utility' },
  { id: 'minecraft:end_crystal', name: 'End Crystal', nameZh: '末影水晶', color: '#CC7ACC', hardness: 0.0, transparent: true, category: 'utility' },
  { id: 'minecraft:ender_eye', name: 'Eye of Ender', nameZh: '末影之眼', color: '#3A9A3A', hardness: 0.0, transparent: false, category: 'utility' },
  { id: 'minecraft:fire_charge', name: 'Fire Charge', nameZh: '火焰弹', color: '#CC3333', hardness: 0.0, transparent: false, category: 'utility' },
]

export function getBlockById(id: string): BlockData | undefined {
  return BLOCKS.find(b => b.id === id)
}

export function getBlocksByCategory(category: BlockCategory): BlockData[] {
  return BLOCKS.filter(b => b.category === category)
}

export function searchBlocks(query: string): BlockData[] {
  const lowerQuery = query.toLowerCase()
  return BLOCKS.filter(b => 
    b.id.toLowerCase().includes(lowerQuery) ||
    b.name.toLowerCase().includes(lowerQuery) ||
    b.nameZh.includes(query)
  )
}
